"""All commands selectable by player AI."""

from enum import Enum


class PlayerCommand(Enum):
    """A single movement, football action or skill command."""

    IDLE = "待機"
    HOLD_POSITION = "ポジション維持"
    KICK = "キック"
    PASS = "パス"
    THROUGH_PASS = "スルーパス"
    CROSS = "クロス"
    SHOOT = "シュート"
    CLEAR = "クリア"
    SLIDE_TACKLE = "スライディング"
    TACKLE = "タックル"
    HEADER = "ヘディング"
    TRAP = "トラップ"
    DRIBBLE = "ドリブル"
    KEEP_BALL = "ボールキープ"
    DASH = "ダッシュ"
    WALK = "ウォーク"
    INTERCEPT_PASS = "パスカット"
    BLOCK_SHOT = "シュートカット"
    RETURN_POSITION = "ポジションへ戻る"
    FOLLOW_BALL = "ボールを追従する"
    RECOVER_LOOSE_BALL = "こぼれ球を拾う"
    RECEIVE_PASS = "パスを受ける"
    PRESS = "プレス"
    MARK = "マーク"
    COVER = "カバー"
    SUPPORT = "サポート"
    TRIANGLE_SUPPORT = "トライアングルを作る"
    LOSE_MARK = "マークを外す"
    CREATE_PASS_LANE = "パスコースを作る"
    OVERLAP = "オーバーラップ"
    DIAGONAL_RUN = "ダイアゴナルラン"
    RUN_INTO_SPACE = "スペースへ走り込む"
    WAIT_IN_FRONT_OF_GOAL = "ゴール前待機"
    GUARD_GOAL = "ゴールを守る"
    SAVE = "セーブ"
    CATCH = "キャッチ"
    PUNCH = "パンチング"
    KEEPER_THROW = "GKスロー"
    KEEPER_PUNT = "GKロングキック"
    THROW_IN = "スローイン"
    FREE_KICK = "フリーキック"
    PENALTY_KICK = "ペナルティキック"
    GOAL_KICK = "ゴールキック"
    CORNER_KICK = "コーナーキック"
    STAGGER = "弾き飛ばされる"
    SKILL_AERIAL_HEADER = "スキル：エアリアルヘッド"
    SKILL_SLIDE_FINISH = "スキル：スライドフィニッシュ"
    SKILL_ARC_CURVE = "スキル：アークカーブ"
    SKILL_WOBBLE_BALL = "スキル：揺らぎ弾"
    SKILL_CHANCE_SENSOR = "スキル：決定機センサー"
    SKILL_MAGIC_PLACE_KICK = "スキル：魔術師のプレースキック"
    SKILL_FORTRESS_BLOCK = "スキル：城塞ブロック"
    SKILL_SPIN_TURN = "スキル：スピンターン"
    SKILL_CLOSE_LOCK = "スキル：密着封鎖"
    SKILL_VACANT_COVER = "スキル：空白カバー"
    SKILL_BACKLINE_HUNTER = "スキル：背後の狩人"
    SKILL_PIVOT_KEEP = "スキル：楔のキープ"
    SKILL_ONE_TOUCH_RELAY = "スキル：ワンタッチリレー"
    SKILL_CARRY_SHOT = "スキル：キャリーショット"
    SKILL_UNBREAKABLE_HEART = "スキル：不屈の心"
    SKILL_OVERLOAD = "スキル：オーバーロード"
    SKILL_RECOVERY_CHASE = "スキル：リカバリーチェイス"
    SKILL_TURNOVER_COUNTER = "スキル：奪取カウンター"
    SKILL_HEEL_REVERSE_TURN = "スキル：反転ヒールターン"
    SKILL_STABLE_CORE = "スキル：不動の体幹"
    SKILL_OVERHEAD_VOLLEY = "スキル：オーバーヘッドボレー"
    SKILL_HALFWAY_CANNON = "スキル：ハーフウェイ砲"
    SKILL_TIGHT_TOUCH = "スキル：タイトタッチ"
    SKILL_SPRINT_CARRY = "スキル：スプリントキャリー"
    SKILL_ENERGY_KEEP = "スキル：エナジーキープ"
    SKILL_COOLDOWN_REST = "スキル：クールダウン休息"
    SKILL_POWER_SLIDE = "スキル：パワースライド"
    SKILL_ONE_WAY_BLOCK = "スキル：片道封鎖"
    SKILL_BLIND_FEED = "スキル：ブラインドフィード"
    SKILL_SIGNAL_LINK = "スキル：サイン連携"
    SKILL_LAST_CHANCE_CANNON = "スキル：ラストチャンス砲"
    SKILL_SAVING_AURA = "スキル：セービングオーラ"
    SKILL_EARLY_READ_SAVE = "スキル：先読みセーブ"
    SKILL_CANNON_MIDDLE = "スキル：キャノンミドル"
    SKILL_DIRECT_VOLLEY = "スキル：ダイレクトボレー"
    SKILL_SET_AND_SHOOT = "スキル：セット＆シュート"
    SKILL_ILLUSION_STEP = "スキル：幻惑ステップ"
    SKILL_RELENTLESS_PRESS = "スキル：猛追プレス"
    SKILL_FUTURE_READ = "スキル：フューチャーリード"
    SKILL_SWEEPER_KEEPER = "スキル：スイーパーキーパー"


__all__ = ("PlayerCommand",)
